# Generated by Django 5.1.1 on 2025-03-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_genre_remove_readingmaterial_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingtext',
            name='content',
            field=models.BinaryField(null=True),
        ),
    ]
