# Generated by Django 5.1.1 on 2025-03-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_speakingtext_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='upload_time',
        ),
    ]
