# Generated by Django 5.2 on 2025-04-10 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_audio_audio_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPracticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(blank=True, help_text='Pronunciation score (e.g., 0-100)', null=True)),
                ('details', models.JSONField(blank=True, help_text='Detailed feedback or identified errors in JSON format', null=True)),
                ('speaking_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_logs', to='app.speakingtext')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Practice Log',
                'verbose_name_plural': 'User Practice Logs',
                'ordering': ['-practice_date'],
            },
        ),
    ]
