# Generated by Django 5.1.1 on 2025-04-08 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_audio_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('speaking_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_results', to='app.speakingtext')),
            ],
        ),
    ]
