# Generated by Django 5.1.1 on 2025-04-14 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingtext',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.level'),
        ),
    ]
