# Generated by Django 5.2 on 2025-04-28 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userpracticelog'),
        ('app', '0014_alter_useraudio_user'),
    ]

    operations = [
    ]
